### ISSUE TITLE
Desaparecieron las  gráficas de comparación con otros países

### ISSUE THREAD

**Issue by AngelRodriguez8008** [covid19cubadata/covid19cubadata.github.io#119]
Hasta hace un par de días se mostraban 2 gráficos de comparación de la Evolución de Cuba con respecto a otros países. En escala lineal (un país) y logarítmica (varios países). 

Esto es muy practico para hacer un análisis de la Pandemia a nivel global. (recuperarlo, por favor)

Si es posible incluir el la posibilidad, no solo logarítmica, si no también lineal con varios países a la vez, por día. Y logarítmica por días, en lugar de 7 días.

Háganme saber si puedo contribuir. Gracias

**Comment by AngelRodriguez8008** [comment]
Puede que se resuelva con el PR #97

**Comment by sandypm007** [comment]
No, incluimos un menú para distribuir la información pues ya había bastante carga en una misma pantalla.

https://covid19cubadata.github.io/worl.html

**Comment by AngelRodriguez8008** [comment]
@sandypm007 Listo, no lo había visto gracias .
