### ISSUE TITLE
Tests acumulados por días

### ISSUE THREAD

**Issue by yaimez** [covid19cubadata/covid19cubadata.github.io#15]
La última fecha del gráfico "Test acumulados por días" dice 03/20, y los datos corresponden a 03/30. Adjunto imagen señalando el problema.
![fecha test acumulados](https://user-images.githubusercontent.com/50188731/78050651-8a1aae80-734a-11ea-92ad-3ee1f3ce1841.png)

**Comment by sandypm007** [comment]
Un error al subir los datos, ya está resuelto.

**Comment by covid19cubadata** [comment]
Fue un typo al subir los datos. Desde ayer fue arreglado.
