### ISSUE TITLE
Faltan casos de Holguin reportados en Parte 24 de junio de 2021

### ISSUE THREAD

**Issue by afercuba** [covid19cubadata/covid19cubadata.github.io#161]
Parte de cierre del día 24 de junio a las 12 de la noche

Holguín: 129 casos

Gibara: 4 (2 contactos de casos confirmados y 2 importados).
Holguín: 60 (42 contactos de casos confirmados, 2 importados y 16 sin fuente de infección precisada).

https://salud.msp.gob.cu/parte-de-cierre-del-dia-24-de-junio-a-las-12-de-la-noche-2/

Saludos
Adrian Fernandez Cuba

PD
Tienen ustedes alguna via o canal para dialogar estos asuntos???

**Comment by leynier** [comment]
Buenas @afercuba tenemos un canal y un grupo en Telegram.

Canal: https://t.me/covid19cubadata
Grupo: https://t.me/joinchat/TfJMJVPnNitwaVOp

Saludos

**Comment by yudivian** [comment]
Hola, efectivamente hubo un error, los códigos de los municipios de mayaría y holguín, fueron cambiados por códigos de santiago, el 32 - código de holguín- por 34 código de Santiago. Por ello aparecía menos casos en Holguí y más en Santiago pero el total estaba bien. Gracias por hacerlo notar. Ya  lo subsanamos. Esto es un trabajo de todos y cualquier colaboración como la suya nos permite un mejor trabajo. Muchas gracias!
