### ISSUE TITLE
CASOS INTERCAMBIADOS DE MUNICIPIO

### ISSUE THREAD

**Issue by afercuba** [covid19cubadata/covid19cubadata.github.io#162]
Hola

En Parte 1/07/21 reportan 4 casos en el municipio Antilla, los cuales pertenecen al municipio Báguanos, de la provincia Holguín. Saludos, gracias por sostener el proyecto.

**Comment by yudivian** [comment]
Gracias por hacerlo notar. Ya lo corregimos, Es que los códigos de ambos municpios son consecutivos, Antilla 32.04 y Báguanos 32.05, y ahí estuvo el error. Gracias de nuevo por contribuir con el proyecto.
