### ISSUE TITLE
Comparación con otros países

### ISSUE THREAD

**Issue by PhaserEditor2D** [covid19cubadata/covid19cubadata.github.io#2]
Seria bueno si pudiésemos compararnos con otros países. Por ejemplo, dado un día determinado (ej. el 10 después del primer caso), ver los demás países cuales eran el número de casos. No tienen que ser todos los países, pueden ser algunos del área y otros que sobresalen por lo bien o mal que están lidiando con la crisis.

**Comment by dolivera77** [comment]
Muy buen trabajo, igual creo q comparar con otros países sería genial

**Comment by leynier** [comment]
This issue should be closed

**Comment by PhaserEditor2D** [comment]
Gracias!
