### ISSUE TITLE
Tests realizados diariamente es mas relevante que el acumulado

### ISSUE THREAD

**Issue by yoelrc88** [covid19cubadata/covid19cubadata.github.io#20]
Como yo lo veo, es mas relevante mostrar como cambia la capacidad diaria de test que el acumulado que se muestra en la grafica "Tests acumulados por días". Por tanto preferiria ver en esta grafica los test realizados diarios sacados de los reportes del MINSAP y Cubadebate.

Por ejemplo: https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/testing-in-us.html
 
Gracias

**Comment by yaimez** [comment]
Si, a mi también me parece más relevante el gráfico de test diarios realizados y de ellos cuántos son positivos, y no con el acumulado.
En el gráfico "Relación de tests realizados" ya se puede ver el acumulado de test realizados y los % de test positivos y negativos. Quizás en este mismo gráfico donde mismo ponen del acumulado el % de los positivos y negativos, agregar el número de casos y ya está toda la información sobre el acumulado.
Muchas gracias y gran trabajo!

**Comment by covid19cubadata** [comment]
Inicialmente se pusieron los acumulados porque eran muy pocos, Ya hoy cambiaremos a diarios.
