### ISSUE TITLE
Distribución por nacionalidad de casos extranjeros ya no es tan importante

### ISSUE THREAD

**Issue by yoelrc88** [covid19cubadata/covid19cubadata.github.io#21]
Quizas inicialmente esta informacion era importante pero a medida que avanza el contagio esta distribucion de nacionales/extranjeros pierde un poco el sentido, ademas ya esta restringido el viaje a la isla por lo tanto el % de cubanos en esta distribucion predominara a partir de ahora. 
Mi sugerencia es quitar esta grafica de "Distribución por nacionalidad de casos extranjeros". Que utilidad tiene ahora saber que importamos mas casos desde Francia que de Espana?
Quizas dejar solo la de "Casos por nacionalidad" que es mas general.
Gracias!

**Comment by yoisel** [comment]
Valdría la pena también en la gráfica de distribución por edad, adicionar indicadores del porciento de la población general que cada sector de edad representa. Por ejemplo los de 41-60 son mayoritarios en el contagio, pero no hay cómo saber desde la gráfica si también son mayoritarios en el porcentage respecto a la pobación general (lo que explicaría que el contagio en ese segmento de edad sea mayor).  Está un poco trabalengüístico, espero se entienda.

**Comment by covid19cubadata** [comment]
En el caso de las nacionalidades por paises estas siguen apareciendo, menos, pero siguen. Para algunos sigue siendo información importante y no afecta su presencia. En el caso de los valores que representa en la población cubana cada rango etario hay que pensar como hacerlo para que el gráfico se siga entendiendo que es el objetivo primario. Slds

**Comment by yoisel** [comment]
Propuesta para el gráfico etario:

El eje "Y" del gráfico podría ponerse en términos de porcientos en lugar de cantidad absoluta (el tooltip seguiría mostrando la cantidad absoluta).

Eso permitiría adicionar una barra al lado con el porcentage de cada rango etario según la población general para poder comparar.
