### ISSUE TITLE
La actualizacion de datos diarios se hace manual? 

### ISSUE THREAD

**Issue by yoelrc88** [covid19cubadata/covid19cubadata.github.io#22]
Mi pregunta sobre si se hace manual viene a que si ha habido algun intento de automatizar este proceso. Asumo que estan adquiriendo la informacion diaria de sitios como cubadebate y del MINSAP. 
Quizas debieramos pedir que compartieran informacion organizada en un excel, CSV, JSON etc. Ellos la deben tener organizada. 
Ya tienen accesso a esta informacion diaria de manera organizada o estan sancandola manualmente de los websites? 

Gracias!

**Comment by HugoLTHdez** [comment]
es manual, segun contacte a su creador hace dias

**Comment by sandypm007** [comment]
La actualización es un proceso manual, hemos estado trabajando en automatizar el proceso por nuestra via en https://github.com/CUSOBU/python.minsap.parser pero de momento no lo hemos estabilizado. Si alguien tiene los contactos adecuados nos simplificaría mucho trabajo llegar a la información primaria incluso si tenemos que desarrollar alguna solución para lograrlo.

**Comment by covid19cubadata** [comment]
Acutalmente es manual a partir de los reportes publicados en el sitio web del minsap. Seguimos trabajando en post de automatizar el proceso pero hasta ahora no ocurre así.
