### ISSUE TITLE
Sugerencia para Grafica y Mapa

### ISSUE THREAD

**Issue by HugoLTHdez** [covid19cubadata/covid19cubadata.github.io#3]
Agreguenle a la grafica de casos positivos, los curados.

**Comment by HugoLTHdez** [comment]
Al grafico del mapa, seria bueno agregarle la opcion de ver, ademas segun la distribucion, sugiero por tipos de casos, ya sean detectados acumulados(es como esta ahora), los casos positivos actuales, y los casos curados.
Ejemplo 
![sugerencia](https://user-images.githubusercontent.com/51713163/78165322-c6184700-7410-11ea-8ccd-e33e0f86e911.png)

**Comment by sandypm007** [comment]
Lo tendremos en cuenta, estamos trabajando para poder acceder a mejores datos y poder plantearnos análisis de ese tipo.

**Comment by eadomenech** [comment]
Hola a todos. Gracias por brindarnos la posibilidad de colaborar en el proyecto. Acá algunas sugerencias.

1- Las gráficas comparativas con otros paises no creo que deba ser. Son muchas las variables como para hacer este tipo de comparación. Propongo que pongan esa misma gráfica pero filtrando por países y no comparando Cuba con otros. Yo dejaría solo la gráfica Evolución de casos por días pudiendo filtrar por país.

2- La gráfica Tests por día a los efectos visuales puede engañarnos, por eso creo que deberíamos add una gráfica de % de casos positivos con respectos a tests realizados, algo como esto 
![Figure_1](https://user-images.githubusercontent.com/11457046/78381461-64d4ad00-75a3-11ea-9c5d-4d1205836a61.png)

Un abrazo

**Comment by covid19cubadata** [comment]
Consideraremos sus ideas dentro del equipo. Slds.
