### ISSUE TITLE
Invitación para integración de Dataset a nivel latinoamérica

### ISSUE THREAD

**Issue by pablodz** [covid19cubadata/covid19cubadata.github.io#32]
Hola, junto con una organización sin fines de lucro se está tratando de centralizar la información de contagiados/muertos/recuperados covid-19 y estamos buscando un encargado por país. En este caso sería Cuba.

El formato de los archivos es el de número de contagiados/muertos/recuperados por departamento por día:

![image](https://user-images.githubusercontent.com/28235457/77831081-ee473380-70fa-11ea-9feb-43fcc0a4f703.png)

Dentro de cada archivo (.csv) respectivo al caso total hasta ese día se tiene que rellenar las siguientes filas:
Por ejemplo para el día [2020-03-28](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/latam_covid_19_data/latam_covid_19_daily_reports/2020-03-28.csv)

![image](https://user-images.githubusercontent.com/28235457/78337638-e2260080-7556-11ea-9729-1094ee4f8142.png)

Podrías comentarme si estás interesado en aportar porfavor.
El dataset centralizado se propone en este repositorio: https://github.com/DataScienceResearchPeru/covid-19_latinoamerica
Se te puede dar acceso nivel `Maintainer` al repositorio mencionado, ya hay encargados de varios países. Caso contrario puedes comentarnos de alguna persona que sí podría apoyarnos. 

Actualización: Ya contamos con un API

**Comment by yudivian** [comment]
Perfecto, creo que podríamos contribuir con la data que tenemos. Luego
podemos ver como hacerlo de la forma más efectiva.

**Comment by pablodz** [comment]
@yudivian claro, nos lo comunicas por [Slack porfa ](https://join.slack.com/t/covid19latinoamerica/shared_invite/zt-d99sp09d-mcwZ3AmFI_kmj~kYryg74w)

**Comment by pablodz** [comment]
Te voy agregando al repositorio con nivel `Maintainer`, sería bueno llamar a otros colaboradores para que te puedan ayudar a subir data, lo mejor es intercalarse los días de subida.
