### ISSUE TITLE
Improve comparative tables Cuba vs Country X

### ISSUE THREAD

**Issue by llamaret** [covid19cubadata/covid19cubadata.github.io#41]
Greetings.
The comparative table of Cases is perfect (Cuba vs. any Country). Some doctors have asked me why the same is not included but with the deaths and those recovered. That is, three comparatives:
-The one we already have [Daily cases Cuba vs. Country X]
- Daily deaths Cuba vs Country X
- Recovered newspapers Cuba vs Country X

It is simply in the Action that it is obtained in addition to the JSON of the daily cases of all the countries, another with the Deaths and another with the Recovered.
And add those last two graphs to the DASH

**Comment by leynier** [comment]
This issue should be closed

**Comment by eadomenech** [comment]
Hola.
Creo una vez haberlo comentado, pero acá va de nuevo. La gráfica comparativa de Cuba con el resto de los paises aunque visualmente es aceptable no creo sea una justa o correcta comparación.

-  Las condiciones del primer día para los países que se comparan (por ejemplo Cuva vs España) no son la misma. Cuando en Cuba se reportó el primer caso el virus ya estaba bastante regado por todo el mundo y España creo que fué uno de los primeros países en adquirirlo, por lo que comparar estos países iniciando desde el día 0 de cada uno de ellos no creo sea correcto. En el ejemplo miren como España estuvo hasta el día 24 sólo con 2 casos, con Italia pasa algo similar. Cualquiera que haga la comparación de Cuba con España o Italia teniendo en cuenta hasta el día 24 dirá "Si Cuba está peor que España e Italia preparémonos para 30000 fallecidos", algo que no creo.

-  La cantidad de habitantes no es ni similar, por lo que comparar con el número de acumulados o diario no creo sea correcto. Por lo menos deberíamos comparar con el número de confirmados x cada 100 mil habitantes.

Existen otros elementos que de igual manera hacen que estas comparaciones no sean, en mi opinión, correctas. Es solo lo que pienso ehh.

**Comment by llamaret** [comment]
> This issue should be closed

You're right. The issue goal has already been met and by far
