### ISSUE TITLE
Adicionar dominio propio

### ISSUE THREAD

**Issue by jkyberneees** [covid19cubadata/covid19cubadata.github.io#43]
Hola, primero que nada felicitaciones por este proyecto tan necesario. Excelente!

Quería preguntar por la posibilidad de tener un dominio propio para este dashboard? 
En caso de poder ayudarles desde el punto de vista de financiación o gestión para adquirir el dominio, estaría muy dispuesto a contribuir. 

Saludos cordiales y gracias nuevamente por este proyecto.

**Comment by sandypm007** [comment]
Estamos manteniendolo en github de momento como algo independiente, en caso de cambiar las necesidades lo tendremos en cuenta, muchas gracias.
