### ISSUE TITLE
New daily test and total tests performed should also be included in the data

### ISSUE THREAD

**Issue by yoelrc88** [covid19cubadata/covid19cubadata.github.io#6]
Info can be collected from:
- http://www.cubadebate.cu/noticias/2020/03/26/cuba-confirma-10-pacientes-positivos-a-la-covid-19-la-cifra-de-casos-asciende-a-67/#.XnzLo9JKip0
- https://salud.msp.gob.cu/?p=4331
- https://twitter.com/minsapcuba links posted

Example on March 26:
"Hasta el momento se han realizado 893 muestras para detectar la COVID-19, de las cuales han resultado positivas los 67 casos acumulados hasta el momento."_

**Comment by e-mayo** [comment]
I believe the accurate location of the samples for the test it's also useful. And data as the people movement like the number of passenger on the public transport daily may be useful to see the actual impact on the infection propagation.

**Comment by yoelrc88** [comment]
Closing this issue, test data was added https://github.com/covid19cubadata/covid19cubadata.github.io/commit/c0afc8209e664f33a16fde0ce67ac5751c532805
Thanks for this work!
