### ISSUE TITLE
Cuando se muestra solo una provincia en el mapa los marker del resto del pais siguen visibles

### ISSUE THREAD

**Issue by LongJohnSilver1504** [covid19cubadata/covid19cubadata.github.io#91]
Cuando se muestra solo una provincia en el mapa los marker del resto del pais siguen visibles.
Creo q solo deberian mostrarse los marker de la provincia q se esta visualizando en ese momento

**Comment by covid19cubadata** [comment]
Gracias. Ya se trabajaba en eso y ya se concluyó el issue. Cualquier otro detalle le agradecemos nos lo reporte.
